using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RootLibrary.Common
{
    public enum Banks
    {
        ADBL,
        NIBL ,
        NMB ,
        NABIL,
        SBI ,
        NIC ,
        HBL ,
        EBL ,
        PRABHU ,
        MACHHAPUCHHRE,
        NEPAL ,
        EVEREST ,
        CITIZENS ,
        SANIMA,
        KUMARI,
        LAXMI,
        MEGA,
        JANATA,
        PRIME,
        SIDDHARTHA ,
        KIST,
        CIVIL,
        TRISTAR ,
        GUHESWORI ,
        KAILASH ,
        KASTHAMANDAP ,
        KARNALI ,
        MOUNTAIN,
        AgriculturalDevelopmentBank,
        BankOfKathmandu,
        CenturyCommercialBank,
        CitizensBankInternational,
        CivilBank,
        EverestBank,
        GlobalIMEBank,
        HimalayanBank,
        JanataBankNepal,
        KumariBank,
        LaxmiBank,
        MachhapuchchhreBank,
        MegaBank,
        NabilBank,
        NepalBangladeshBank,
        NepalBankLimited,
        NepalCreditAndCommerceBank,
        NepalInvestmentBank,
        NepalRastraBank,
        NepalSBIbank,
        NepalSaudiBank,
        NICAsiaBank,
        NMBBank,
        PrabhuBank,
        PrimeCommercialBank,
        RastriyaBanijyaBank,
        SanimaBank,
        SiddharthaBank,
        StandardCharteredBank,
        SunriseBank,
        TourismDevelopmentBank,
        TrishuliBikasBank,
        CitizensBankInternationalLimited,
        GandakiBikasBankLimited,
        GarimaBikasBankLimited,
        ICFCFinanceLimited,
        InfinityLaghubittaBittiyaSansthaLimited,
        JanataBankNepalLimited,
        KamanaSewaBikasBankLimited,
        KankaiBikasBankLimited,
    }
}
